# AUTO-GENERATED BY calibration_analysis_v2_script.py
# Run this script to update formulas.

# Pan Calculation Function (Degree 4)
def calculate_pan(x, y):
    val = 155.6668858701
    val += 0.4560199871 * (x)
    val += 0.7342655133 * (y)
    val += -0.0035976159 * (x**2)
    val += -0.0043827793 * (x*y)
    val += -0.0084661672 * (y**2)
    val += 0.0000057403 * (x**3)
    val += 0.0000133400 * (x**2*y)
    val += 0.0000101783 * (x*y**2)
    val += 0.0000536484 * (y**3)
    val += -0.0000000029 * (x**4)
    val += -0.0000000106 * (x**3*y)
    val += -0.0000000180 * (x**2*y**2)
    val += 0.0000000082 * (x*y**3)
    val += -0.0000001569 * (y**4)
    return val

# Tilt Calculation Function (Degree 4)
def calculate_tilt(x, y):
    val = 113.6717028380
    val += 0.3335993613 * (x)
    val += -0.6916488737 * (y)
    val += -0.0008407415 * (x**2)
    val += -0.0009024326 * (x*y)
    val += 0.0084145572 * (y**2)
    val += 0.0000005454 * (x**3)
    val += 0.0000028613 * (x**2*y)
    val += 0.0000022977 * (x*y**2)
    val += -0.0000683027 * (y**3)
    val += 0.0000000001 * (x**4)
    val += -0.0000000038 * (x**3*y)
    val += 0.0000000088 * (x**2*y**2)
    val += -0.0000000351 * (x*y**3)
    val += 0.0000002091 * (y**4)
    return val

