import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn.metrics import mean_squared_error
import sys

# 1. LOAD DATA
print("--- Loading Data ---")
csv_path = "data/calibration_points.csv"
try:
    df = pd.read_csv(csv_path, names=["camera_x", "camera_y", "servo_pan", "servo_tilt"])
    # Clean non-numeric rows if any remain
    df = df.apply(pd.to_numeric, errors='coerce').dropna()
    df = df.drop_duplicates()
    print(f"Loaded {len(df)} Unique Points.")
except Exception as e:
    print(f"Error loading {csv_path}: {e}")
    sys.exit(1)

# 2. FIT MODELS
def fit_all(X, y, label):
    best_deg = 1
    best_rmse = 999
    best_model = None
    
    print(f"--- {label} Models ---")
    for d in [1, 2, 3, 4]:
        model = make_pipeline(PolynomialFeatures(d), LinearRegression())
        model.fit(X, y)
        pred = model.predict(X)
        rmse = np.sqrt(mean_squared_error(y, pred))
        print(f"Degree {d}: Fit Error = {rmse:.2f}°")
        
        if rmse < best_rmse:
            best_rmse = rmse
            best_deg = d
            best_model = model
            
    print(f"🏆 Best Fit: Degree {best_deg}\n")
    return best_model, best_deg

X = df[['camera_x', 'camera_y']]
pan_model, pan_deg = fit_all(X, df['servo_pan'], "Pan")
tilt_model, tilt_deg = fit_all(X, df['servo_tilt'], "Tilt")

# 3. EXPORT TO FILE
def export_best_functions(pan_model, pan_deg, tilt_model, tilt_deg):
    filepath = "tools/calibration_config.py"
    
    output_lines = []
    output_lines.append("# AUTO-GENERATED BY calibration_analysis_v2_script.py\n")
    output_lines.append("# Run this script to update formulas.\n\n")
    
    def generate_func_str(model, degree, name):
        poly = model.named_steps['polynomialfeatures']
        reg = model.named_steps['linearregression']
        features = poly.get_feature_names_out()
        coefs = reg.coef_
        intercept = reg.intercept_
        
        lines = []
        lines.append(f"# {name} Calculation Function (Degree {degree})\n")
        lines.append(f"def calculate_{name.lower()}(x, y):\n")
        lines.append(f"    val = {intercept:.10f}\n")
        for feat, c in zip(features, coefs):
            if feat == "1": continue
            term = feat.replace(" ", "*").replace("^", "**")
            term = term.replace("camera_x", "x").replace("camera_y", "y")
            lines.append(f"    val += {c:.10f} * ({term})\n")
        lines.append("    return val\n\n")
        return lines

    output_lines.extend(generate_func_str(pan_model, pan_deg, "Pan"))
    output_lines.extend(generate_func_str(tilt_model, tilt_deg, "Tilt"))
    
    with open(filepath, "w") as f:
        f.writelines(output_lines)
        
    print(f"✅ SUCCESS: Formulas written to {filepath}")
    print("👇 HERE ARE YOUR FORMULAS 👇")
    print("".join(output_lines))

export_best_functions(pan_model, pan_deg, tilt_model, tilt_deg)
print("\nNow run: python3 tools/test_calibration_live.py")
